# Architecture
arch: cResNet18

# ===== Dataset ===== #
data: /s/luffy/b/nobackup/mgorb/data
set: CIFAR10
name: baseline

# ===== Learning Rate Policy ======== #
optimizer: sgd
lr: 0.1
lr_policy: cosine_lr
warmup_length: 5
# ===== Network training config ===== #
epochs: 250
weight_decay: 0.0001
momentum: 0.9
batch_size: 256

# ===== Sparsity =========== #
conv_type: SubnetConvEdgePopup
bn_type: NonAffineBatchNorm
freeze_weights: True
prune_rate: -1

rerand_epoch_freq: 3
rerand_rate: 0.1
rerand_type: recycle

weight_init: signed_constant
score_init: None
weight_seed: 0
score_seed: 0

gpu: 4
# ===== Hardware setup ===== #
workers: 4
