arch: ResNet18

# ===== Dataset ===== #
data: /s/babbage/b/nobackup/nblancha/public-datasets/subnetworks/
set: ImageNet
name: tiled

# ===== Learning Rate Policy ======== #
optimizer: sgd
#lr: 0.1 
lr: 0.256
lr_policy: cosine_lr
warmup_length: 5

# ===== Network training config ===== #
epochs: 300
total_epochs: 400
weight_decay: 0.000030517578125
#weight_decay: 0.0001
momentum: 0.875
batch_size: 256
label_smoothing: 0.1


# ===== Sparsity =========== #
layer_type: SubnetConvTiledFull

global_compression_factor: 4
min_compress_size: 132000
#global_compression_factor: 4
#layer_compression_factors: 1,1,1,1,1,2,4,1,4,4,4,4,1,4,4,4,4,1,4,4,4

model_type: binarize
alpha_type: multiple


#data_type: float16




#bn_type: NonAffineBatchNorm
bn_type: LearnedBatchNorm

weight_init: kaiming_normal
scale_fan: True
score_init: None



# ===== Hardware setup ===== #
workers: 20