#USED FOR EVALUATION ONLY
#SET ARCH ON COMMAND LINE BEFORE RUNNINGN

# Architecture
#arch: ResNet

# ===== Dataset ===== #
data: /s/luffy/b/nobackup/mgorb/
set: ImageNet
name: baseline

# ===== Learning Rate Policy ======== #
optimizer: sgd
lr: 0.01
lr_policy: cosine_lr

# ===== Network training config ===== #
epochs: 100
weight_decay: 0.0001
momentum: 0.9
batch_size: 128

# ===== Sparsity =========== #
conv_type: DenseConv
bn_type: NonAffineBatchNorm

weight_init: kaiming_normal
score_init: None
weight_seed: 0
score_seed: 0
gpu: 6

# ===== Hardware setup ===== #
workers: 4
