arch: ResNet34

# ===== Dataset ===== #
data: /s/babbage/b/nobackup/nblancha/public-datasets/subnetworks/
set: ImageNet
name: tiled

# ===== Learning Rate Policy ======== #
optimizer: sgd
lr: 0.256
#lr: 0.1
lr_policy: cosine_lr
warmup_length: 5

# ===== Network training config ===== #
epochs: 300
total_epochs: 400
weight_decay: 0.000030517578125
#weight_decay: 0.0001
momentum: 0.875
batch_size: 256
label_smoothing: 0.1


# ===== Sparsity =========== #
layer_type: SubnetConvTiledFull
global_compression_factor: 4
min_compress_size: 132000
#layer_compression_factors: 1,1,1,1,1,1,1,2,4,1,4,4,4,4,4,4,4,4,1,4,4,4,4,4,4,4,4,4,4,4,4,1,4,4,4,4,4

model_type: binarize
alpha_type: multiple


#data_type: float16

multigpu: 0,1,2,3,4,5,6,7
ngpus_per_node: 6


#bn_type: NonAffineBatchNorm
bn_type: LearnedBatchNorm

prune_rate: -1 # Override1=2
weight_init: kaiming_normal
mode: fan_in
nonlinearity: relu
scale_fan: True



# ===== Hardware setup ===== #
workers: 20