arch: WideResNet50_2

# ===== Dataset ===== #
data: /s/babbage/b/nobackup/nblancha/public-datasets/subnetworks/
set: ImageNet
name: biprop

# ===== Learning Rate Policy ======== #
optimizer: sgd
lr: 0.256
lr_policy: cosine_lr
warmup_length: 5

# ===== Network training config ===== #
epochs: 100
weight_decay: 0.000030517578125
momentum: 0.875
batch_size: 256
label_smoothing: 0.1


# ===== Sparsity =========== #

conv_type: SubnetConvBiprop
data_type: float16
multigpu: 2,3,4,5,6,7
ngpus_per_node: 6


#bn_type: NonAffineBatchNorm
bn_type: LearnedBatchNorm
freeze_weights: True
prune_rate: -1 # Override1=2
weight_init: kaiming_normal
mode: fan_in
nonlinearity: relu
scale_fan: True



# ===== Hardware setup ===== #
workers: 20