# Architecture
arch: Conv6

# ===== Dataset ===== #
data: /s/luffy/b/nobackup/mgorb/data
set: CIFAR10
name: conv6_arg_baseline

# ===== Learning Rate Policy ======== #
optimizer: adam
lr: 0.0003

# ===== Network training config ===== #
epochs: 100
batch_size: 60

# ===== Sparsity =========== #
conv_type: RGConv
bn_type: NonAffineBatchNorm

# ===== Hardware setup ===== #
workers: 4
log_dir: /s/luffy/b/nobackup/mgorb/data/runs/baseline