# Architecture
arch: Conv6

# ===== Dataset ===== #
data: /s/luffy/b/nobackup/mgorb/data
set: CIFAR10
name: baseline

# ===== Learning Rate Policy ======== #
optimizer: sgd
lr: 0.1
lr_policy: cosine_lr

# ===== Network training config ===== #
epochs: 500
weight_decay: 0.0001
momentum: 0.9
batch_size: 128

# ===== Sparsity =========== #
conv_type: SubnetConv
bn_type: NonAffineBatchNorm
freeze_weights: True

weight_init: signed_constant
score_init: None
weight_seed: 0
score_seed: 0
rerand_freq: 50
rerand_rate: 0.1
rerand_type: iterand

gpu: 2
seed: 1
# ===== Hardware setup ===== #
workers: 4
