# Architecture
arch: cResNet18

# ===== Dataset ===== #
data: /s/luffy/b/nobackup/mgorb/data
set: CIFAR10
name: baseline

# ===== Learning Rate Policy ======== #
optimizer: sgd
lr: 0.1
lr_policy: cosine_lr

# ===== Network training config ===== #
epochs: 100
weight_decay: 0.0001
momentum: 0.9
batch_size: 128

# ===== Sparsity =========== #
conv_type: SubnetConvBiprop
bn_type: NonAffineBatchNorm
freeze_weights: True
prune_rate: 0.5
weight_init: kaiming_normal
score_init: None
weight_seed: 0
score_seed: 0

rerand_epoch_freq: 1
rerand_rate: 0.1
rerand_type: recycle

gpu: 0
# ===== Hardware setup ===== #
workers: 4
