# Architecture
arch: cResNet34

# ===== Dataset ===== #
data: /s/luffy/b/nobackup/mgorb/data
set: CIFAR10
name: baseline

# ===== Learning Rate Policy ======== #
optimizer: sgd
lr: 0.1
lr_policy: cosine_lr

# ===== Network training config ===== #
epochs: 500
weight_decay: 0.0001
momentum: 0.9
batch_size: 128


layer_type: DenseConv

#weight_tile_size: 65056

#layer_compression_factors: 4,4,4,4,4,4,4,4,4


#bn_type: NonAffineBatchNorm
bn_type: LearnedBatchNorm

#weight_init: kaiming_normal
scale_fan: True
score_init: None



weight_seed: 0
score_seed: 0





gpu: 0
# ===== Hardware setup ===== #
workers: 2